apiVersion: v1
kind: Service
metadata:
  name: tech-challenge-service
spec:
  selector:
    app: tech-challenge-7soat-pod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer