apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: tech-challenge-7soat-api-external-secret
  namespace: default
spec:
  refreshInterval: 72h
  secretStoreRef:
    name: tech-challenge-7soat-api-external-secret-store
    kind: SecretStore
  data:
  - secretKey: DATABASE_URL
    remoteRef:
      key: 7Soat
      property: DATABASE_URL
  - secretKey: POSTGRES_PASSWORD
    remoteRef:
      key: 7Soat
      property: POSTGRES_PASSWORD
  - secretKey: POSTGRES_USER
    remoteRef:
      key: 7Soat
      property: POSTGRES_USER
  - secretKey: POSTGRES_DB
    remoteRef:
      key: 7Soat
      property: POSTGRES_DB
