apiVersion: v1
kind: Service
metadata:
  name: tech-challenge-7soat-api-alb
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "alb"
spec:
  selector:
    app: tech-challenge-7soat-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer